-- Date Functions

-- 1
SELECT CURRENT_DATE FROM DUAL;

-- 2
SELECT EXTRACT(YEAR FROM SYSDATE()) FROM DUAL;

-- 3
SELECT EXTRACT(DAY FROM SYSDATE()) FROM DUAL;

-- 4
SELECT EXTRACT(MONTH FROM SYSDATE()) FROM DUAL;

-- 5
SELECT SYSDATE() FROM DUAL;

-- String Functions

-- 6
SELECT ASCII('a') FROM DUAL;

-- 7
SELECT ASCII('A') FROM DUAL;

-- 8
SELECT ASCII('Z') FROM DUAL;

-- 9
SELECT ASCII('z') FROM DUAL;

-- 10
SELECT UPPER('bldeasb arts and kcp science college') FROM DUAL;

-- 11
SELECT LOWER('WELCOME TO DBMSLAB') FROM DUAL;

-- 12
SELECT REPLACE('HELLO', 'H', 'K') FROM DUAL;

-- 13
SELECT REPLACE('COMPUTER', 'C', 'K') FROM DUAL;

-- 14
SELECT REPLACE('HELLO', 'L', 'A') FROM DUAL;

-- 15
SELECT TRIM('A' FROM 'ANACONDA') FROM DUAL;

-- 16
SELECT LTRIM('ANACONDA') FROM DUAL;

-- 17
SELECT LTRIM('ANIL') FROM DUAL;

-- 18
SELECT RTRIM('ANITA') FROM DUAL;
